export OPERAPLUGINWRAPPER_PRIORITY=0
export EDITOR=vim
export OPERA_KEEP_BLOCKED_PLUGIN=0
export XMODIFIERS="@im=fcitx"
export XIM="fcitx"
export XIM_PROGRAM="fcitx"
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"
export MPD_HOST=/run/user/$UID/mpd/socket
export OPERAPLUGINWRAPPER_PRIORITY=0
export OPERA_KEEP_BLOCKED_PLUGIN=0
export VDPAU_NVIDIA_NO_OVERLAY=1
