;; -*- no-byte-compile: t; -*-
;;; ~/.config/doom/packages.el
(package! evil-terminal-cursor-changer)
(package! lsp-mode)
(package! company-lsp)
(package! ccls)
(package! lsp-ui)
(package! flycheck)
(package! yasnippet)
(package! evil-snipe :disable t)
(package! telephone-line)
;; (package! powerline-evil)
;; (package! flycheck-clang-tidy)
;; (package! helm-rg)
(package! undo-tree :recipe (:fetcher git :url "http://www.dr-qubit.org/git/undo-tree.git/"))
